[supervisord]
nodaemon=true
user=appuser
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:movie_api_node1]
command=java -jar /app/movie_api.jar --server.port=9001
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/movie_api_node1.err.log
stdout_logfile=/var/log/supervisor/movie_api_node1.out.log
environment=SERVER_PORT=9001

[program:movie_api_node2]
command=java -jar /app/movie_api.jar --server.port=9002
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/movie_api_node2.err.log
stdout_logfile=/var/log/supervisor/movie_api_node2.out.log
environment=SERVER_PORT=9002

[program:proxy]
command=java -jar /app/proxy.jar
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/proxy.err.log
stdout_logfile=/var/log/supervisor/proxy.out.log
priority=999
