spring.application.name=proxy
server.port=8080

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000

# Data Warehouse Endpoints (Round-Robin Load Balancing)
datawarehouse.endpoints=http://localhost:9001,http://localhost:9003

# JPA Configuration (optional, if needed)
spring.jpa.hibernate.ddl-auto=none
