spring.application.name=proxy
proxy.backends=http://localhost:9001
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/proxydb
spring.datasource.username=admin
spring.datasource.password=Cascaval24#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
