spring.application.name=sync_node
proxy.url=http://localhost:8080
server.port=9099

spring.datasource.url=jdbc:postgresql://localhost:5432/proxydb
spring.datasource.username=admin
spring.datasource.password=adminpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
